// react/multiple-components-demo.js
var FriendsContainer = React.createClass({
  getInitialState: function(){
    return {
      name: 'Tyler McGinnis',
      friends: ['Jake Lingwall', 'Murphy Randall', 'Merrick Christensen'],
    }
  },
  addFriend: function(friend){
    this.state.friends.push(friend);
    this.setState({
      friends: this.state.friends
    });
  },
  removeFriend: function(indexOfFriendToRemove) {
    this.state.friends.splice(indexOfFriendToRemove,1);
    this.setState({
      friends: this.state.friends
    });
  },
  render: function(){
    return (
      <div>
        <h3> Name: {this.state.name} </h3>
        <AddFriendDialog addNew={this.addFriend} />
        <List items={this.state.friends} removeItem={this.removeFriend} />
      </div>
    )
  }
});

var AddFriendDialog = React.createClass({
  getInitialState: function(){
    return {
      newFriend: ''
    }
  },
  updateNewFriend: function(e){
    this.setState({
      newFriend: e.target.value
    });
  },
  handleAddNew: function(){
    this.props.addNew(this.state.newFriend);
    this.setState({
      newFriend: ''
    });
  },
  render: function(){
    return (
        <div>
          <input type="text" value={this.state.newFriend} onChange={this.updateNewFriend} />
          <button onClick={this.handleAddNew}> Add Friend </button>
        </div>
    );
  }
});

var List = React.createClass({
  handleRemoveItem: function(indexOfItemToRemove) {
    this.props.removeItem(indexOfItemToRemove);
  },
  render: function(){
    var listItems = this.props.items.map (
      (item,index) => (
          <li key={index}> {item} 
            <button onClick={this.handleRemoveItem.bind(null, index)}> Remove </button>
          </li>
        )
      );
    return (
      <div>
        <h3> Friends </h3>
        <ul>
          {listItems}
        </ul>
      </div>
    )
  }
});

window.FriendsContainer = FriendsContainer;

// angular2/app/multiple-components-demo.component.ts
import { Component, Input } from '@angular/core';

@Component({
  selector: 'add-friend-dialog',
  template: `
   <div>
    <input type="text" [(ngModel)]="newFriend" />
    <button (click)=handleAddNew()> Add Friend </button>
  </div>
  `
})
export class AddFriendDialog {
  @Input() 
  addNew: Function;
  
  newFriend: String = '';

  handleAddNew() {
    this.addNew(this.newFriend);
    this.newFriend = '';
  }
}

@Component({
  selector: 'list',
  template: `
    <h3> Friends </h3>
    <ul>
      <li *ngFor="let item of items; let i = index"> 
        {{item}} 
        <button (click)=removeItem(i)> Remove </button>
      </li>
    </ul>
  `
})
export class List {
  @Input()
  items: String[];

  @Input()
  removeItem: Function;
}

@Component({
  selector: 'multiple-components',
  template: `
    <div>
      <h3>Name: {{name}} </h3>
      <add-friend-dialog [addNew]="addFriend"> </add-friend-dialog>
      <list [items]="friends" [removeItem]="removeFriend"> </list>
    </div>
  `,
  directives: [AddFriendDialog, List]
})
export class MultipleComponentsDemoComponent {
  name: String = 'Tyler McGinnis';
  friends: String[] = ['Jake Lingwall', 'Murphy Randall', 'Merrick Christensen'];

  addFriend = (newFriend: String) => {
    this.friends.push(newFriend);
  }

  removeFriend = (index: number) => {
    this.friends.splice(index,1);
  }
}
